### ISSUE TITLE
Followers

### ISSUE THREAD

**Issue by kaptsanovb** [MistyKnives/Kick4J#5]
Is there a way to get followers of a channel?

**Comment by FenaPhoenix** [comment]
This is something I am trying to work on Kaptsanovb, did you manage to get it all working?
When adding the project in eclipse I receive a lot of errors unfortunately

**Comment by kaptsanovb** [comment]
I haven't tried using it , I'm not a Java dev 😅
I am also trying to find a way to get the follower and subscriber list of a specified channel, but it may not be possible until Kick makes an official api.

If you're signed in and load the page of a channel (i.e. kick.com/nibbleglue) 
there are 2 interesting requests:

 - **"user"** to **https://kick.com/api/v1/user**, which looks like this:
```
{
agreed_to_terms: **bool**
apple_id: **not sure about the type, probably string**
bio: **string**
channel_can_be_updated: **bool**
city: **string**
country: **string**
discord: **string**
email: **string**
email_updated_at: **DateTime string probably**
email_verified_at: **DateTime string**
enable_live_notifications: **bool**
enable_onscreen_live_notifications: **bool**
enable_sms_promo: **bool**
enable_sms_security: **bool**
facebook: **string**
filtered_categories: **string[] probably? it's an array**
google_id: **string**
id: **int**
instagram: **string**
intercom_hash: **string or int probably (null for me)**
is_2fa_setup: **bool**
is_live:  **bool**
newsletter_subscribed:  **bool**
phone: **string**
profilepic: **string containing pfp data**
redirect: **string containing url**
roles: **string[] probably? it's an array**
state: **string**
streamer_channel: 
    {
    can_host: **bool**
    id: **int**
    is_banned: **bool**
    name_updated_at: **DateTime string probably**
    playback_url: **string**
    slug: **string**
    subscription_enabled: **bool**
    user_id: **int**
    verified: **bool**
    vod_enabled: **bool**
    }
tiktok: **string**
twitter: **string**
username: **string**
youtube: **string**
}
```

and

- **"me"** to **https://kick.com/api/v2/channels/nibbledglue/me** ,  which looks like this:
```
{
banned: **bool**
following_since: **DateTime string**
has_notifications: **bool**
is_broadcaster: **bool**
is_following: **bool**
is_moderator: **bool**
is_super_admin: **bool**
leaderboards: {gifts: {quantity: **int**}}
subscription: **bool**
}
```

Both of these seem to refer to the account that is signed in, there are headers that I could not wrap my head around but its probably what's carrying the account name to the API endpoint.

In **"user"** there is *`streamer_channel.subscription_enabled`*, and in **"me"** there is *`is_following`* and *`subscription`*

Hope this helps!
